name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-push:
    name: Docker build and push to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: Build, tag, and push image to ACR
      run: |
        cd server/AdminMicroservice
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:${{ github.sha }}

        cd ../server/NotificationMicroservice
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:${{ github.sha }}

        cd ../server/PaymentMicroservice
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:${{ github.sha }}

        cd ../server/UserMicroservice
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:${{ github.sha }}