name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-push:
    name: Docker build and push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Build, tag, and push image to ACR
      #   run: |
      #     docker build server/AdminMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest

      #     docker build server/NotificationMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest

      #     docker build server/PaymentMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest

      #     docker build server/UserMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest

      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: Knowza.io
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: adminserver
          dns-name-label: url-for-container
          environment-variables: LOG_FOLDER='.//logs//' LOG_FILENAME='log_file-%DATE%.log' PORT='8000' JWT_EXPIRE='2 days'
          secure-environment-variables: MONGO_URI=${{ secrets.MONGO_URI }} JWT_SECRET=${{ secrets.JWT_SECRET }} RABBITMQ_URI=${{ secrets.RABBITMQ_URI }}
          location: 'central india'

      - name: Azure logout
        run: |
          az logout
