name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: server/AdminMicroservice
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/admin_microservice:latest



    # runs-on: ubuntu-latest
    # steps:
    
    # - uses: actions/checkout@v2
    # - name: docker login
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    #   run: |
    #     echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        
    # - uses: actions/checkout@v3
    # - name: Build the AdminMicroservice Image
    #   run: |
    #     cd server/AdminMicroservice/
    #     docker build . --tag ${{ secrets.DOCKER_USERNAME }}/admin_microservice
      
    # - name: Docker Push
    #   run: docker push ${{ secrets.DOCKER_USERNAME }}/admin_microservice
