name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-push:
    name: Docker build and push to ACR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
 
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: Build, tag, and push image to ACR
      run: |
        docker build server/AdminMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest

        docker build server/NotificationMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest

        docker build server/PaymentMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest

        docker build server/UserMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest

    - name: Create Container Instances
      env:
        JWT_SECRET: '${{ secrets.JWT_SECRET }}'
        MONGO_URI: '{{ secrets.MONGO_URI }}'
        RABBITMQ_URI: '{{ secrets.RABBITMQ_URI }}'
        REGISTRY_LOGIN_SERVER: '${{ secrets.REGISTRY_LOGIN_SERVER }}'
        REGISTRY_NAME: '${{ secrets.REGISTRY_NAME }}'
        REGISTRY_PASSWORD: '${{ secrets.REGISTRY_PASSWORD }}'
        REGISTRY_USERNAME: '${{ secrets.REGISTRY_USERNAME }}'
        STRIPE_PUBLISHABLE_KEY: '${{ secrets.STRIPE_PUBLISHABLE_KEY }}'
        STRIPE_SECRET_KEY: '${{ secrets.STRIPE_SECRET_KEY }}'
      run: |
        az container create --resource-group Knowza.io --file server/deploy-adminserver.yml

        az container create --resource-group Knowza.io --file server/deploy-userserver.yml

        az container create --resource-group Knowza.io --file server/deploy-paymentserver.yml
    
    - name: Azure logout
      run: |
        az logout