name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-push:
    name: Docker build and push to ACR
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Build, tag, and push image to ACR
      #   run: |
      #     docker build server/AdminMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest

      #     docker build server/NotificationMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/notificationmicroservice:latest

      #     docker build server/PaymentMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/paymentmicroservice:latest

      #     docker build server/UserMicroservice -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/usermicroservice:latest

      - name: Create Container Instances
        run: |
          az container create \
          -g Knowza.io \
          --name adminserver \
          --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/adminmicroservice:latest  \
          --secure-environment-variables ${{ secrets.ADMIN_VARIABLES }} \
          --ip-address Public \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }}

          # az container create --resource-group Knowza.io --file server/deploy-userserver.yml

          # az container create --resource-group Knowza.io --file server/deploy-paymentserver.yml

      - name: Azure logout
        run: |
          az logout
